spring.application.name=dailyNews

spring.datasource.url=jdbc:postgresql://localhost:5432/dailyNews
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=
jwt.expiration=3600000
